# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
app:
  replicaCount: 1
  repository: 153590191236.dkr.ecr.us-east-1.amazonaws.com/genwizard-dedicated-repo-dev
  pullPolicy: Always
  tag: "nginx_1_27"
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  resources:
    limits:
      cpu: "1000m"
      memory: "1024Mi"
    requests:
      cpu: "1000m"
      memory: "1024Mi"

env:
  name: "ASPNETCORE_ENVIRONMENT"
  values: "Development"
  name1: "ASPNETCORE_FORWARDEDHEADERS_ENABLED"
  values1: "true"  

service:
  ports:
    port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP

annotations: 
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/group.name: genwizard-eks
    alb.ingress.kubernetes.io/group.order: '1'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-Ext2-2021-06
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/success-codes: "200-302"
    #alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=true
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:153590191236:certificate/f24cef60-8a43-4b4c-bff6-dabb55fb0b29
    #alb.ingress.kubernetes.io/load-balancer-arn: arn:aws:elasticloadbalancing:us-east-1:153590191236:loadbalancer/app/alb-nvipubdv-genwizard-eks/a484535c97a4a71e

albspec:
  ingressClassName: alb
  rules:
      host: genwizardapi-deveks.accenture.com
      http:
        paths:
          path: /
          pathType: Prefix  #there is an another pathtype called "exact" which is strict unless if it matches the path then only it proceeds.
          backend:
            service:
              name: nginx-svc
              port:
                number: 80
      host1: genwizard-deveks.accenture.com
      http1:
        paths:
          path: /
          pathType: Prefix
          backend:
            service:
              name: nginx-svc
              port:
                number: 80
hpa:
  minReplicas: 1
  maxReplicas: 3
  metrics:
    type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
      name1: memory
      target1:
        type: Utilization
        averageUtilization: 50


#DNS resolves the domain to "externalIP of the loadbalancer" or "NodeIp incase if it is nodeport". 
#The request then reaches to Ingress controller, which matches with host and path and forwards 
#traffic to service clusterIP, and then routes the traffic to pods. 

#so, the thing is DNS is resolving to IP's of the node(incase of nodeport) or loadbalancer IP, not resolving to the type of IP.
